---
- name: Set the Redis configuration file
  template:
    src: redis.conf.j2
    dest: /etc/redis/redis.conf
    owner: redis
    group: redis
    mode: 0640
  notify: "Restart Redis"
  when: redis_server_install
