---
- name: Set the Redis Sentinel configuration file
  template:
    src: sentinel.conf.j2
    dest: /etc/redis/sentinel.conf
    owner: redis
    group: redis
    mode: 0640
  notify: "Restart Redis Sentinel"
  when: redis_sentinel_install
