---
- name: Install latest version of Redis Sentinel
  apt:
    name: redis-sentinel
    state: "{{ redis_sentinel_server_state }}"
    purge: "{{ redis_sentinel_server_purge }}"
  when:
    - redis_sentinel_install
    - redis_sentinel_version == "latest"

- name: Install specific version of Redis Sentinel
  apt:
    name: "redis-sentinel={{ redis_sentinel_version }}"
    state: "{{ redis_sentinel_server_state }}"
    purge: "{{ redis_sentinel_server_purge }}"
  when:
    - redis_sentinel_install
    - redis_sentinel_version != "latest"
